### ISSUE TITLE
Switchback issues

### ISSUE THREAD

**Issue by Primeflux** [Angel-125/Pathfinder#2]
*The KIS mounting node seems to be wrongly placed.
*Saddle does not allow mounting of switchback.

**Comment by Angel-125** [comment]
Should be fixed with 0.8.6. :)

**Comment by Primeflux** [comment]
Sadly the saddle still does not want to play with the switchback.
"allowedPartName = WBI_Switcback" needs to be added to ModuleKISPartMount module
